# Generated by Django 4.1.7 on 2023-03-22 22:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, default=None, null=True, use_json_field=True),
        ),
    ]
